### ISSUE TITLE
Iwsd Sub InspectorのInputField | On End Editが動作しない

### ISSUE THREAD

**Issue by dadenCKEP** [naqtn/ProgrammingInVRChat#2]
https://github.com/naqtn/ProgrammingInVRChat/blob/master/unity/DigAndAnnotate/Assets/iwsd_vrc/Tools/EditSupport/Editor/IwsdSubInspectorWindow.cs
リリース版・開発版ともに動作しませんでした。未実装の場合は実装予定はありますか？
2017.4.15f1にて確認をしました。

**Comment by naqtn** [comment]
InputField に対しては OnValueChanged のみを対象としています。VRChat ワールド開発においてはアニメーションイベントなどから値を変更した時にも動作させるために、OnEndEdit よりもこちらを使う事が多いと聞いたため、こちらの方を選択しました。
暫定的な対処としては 464行からのところ https://github.com/naqtn/ProgrammingInVRChat/blob/master/unity/DigAndAnnotate/Assets/iwsd_vrc/Tools/EditSupport/Editor/IwsdSubInspectorWindow.cs#L464 二行コメントアウトを復活、つづく二行をコメントアウトすると OnEndEdit を対象とするようになると思います。（一時期はそっちで動かしていたため、そのスクショがあったかもしれません）
未実装項目という扱いではありませんでしたが（実装しようという予定には入っていませんでしたが）「OnEndEdit にも使いどころがそれなりにある」ということであれば改造の検討をします。実用的な使いどころ（OnValueChanged では不適当で OnEndEdit を使う、あるいは両方とも使う必要がある状況）はありますか？

**Comment by dadenCKEP** [comment]
正直なところOnValueChangedの使用例をあまり見ておらず、見てきた多くのprefabsではOnEndEditを使用していたため質問した次第です。
ですが、現状両方使う必要があるケースはなく、OnEndEditに対象を変更する方法で十分対応できそうです。ありがとうございます。
