### ISSUE TITLE
OnClick events are broken if you reference a VRC trigger

### ISSUE THREAD

**Issue by JordoVR** [naqtn/ProgrammingInVRChat#3]
Hey! 
Was trying to use the emulator earlier and I noticed that, because you swap the VRC trigger with one of your own, a call to OnClick that was meant for the VRC trigger (Interact() in this case) is not referenced.

**Comment by naqtn** [comment]
Fixed in 93b5da0fd99de7c2f49b70b378be9874c651a917

As you mentioned, because of UnityEngine.UI.Button OnClick referred original VRC_Trigger, Button couldn't invoke VRC_Trigger methods. I fix it by reconnecting reference at runtime.
